# Generated by Django 4.1.1 on 2022-10-03 22:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaLibros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='MaterialBibliografico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(5)])),
                ('autor', models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(5)])),
                ('pais', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(4)])),
                ('cantidadEjemplares', models.PositiveSmallIntegerField()),
                ('cantidadActual', models.PositiveSmallIntegerField()),
                ('fechaPublicacion', models.DateField()),
                ('edicion', models.CharField(blank=True, max_length=45, validators=[django.core.validators.MinLengthValidator(2)])),
                ('idioma', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)])),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.categorialibros')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('apellidos', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('correo', models.EmailField(max_length=45, validators=[django.core.validators.MinLengthValidator(5)])),
                ('numeroTelefonico', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(7)])),
                ('direccion', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(10)])),
                ('ci', models.CharField(max_length=10, unique=True)),
                ('materialPrestado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.materialbibliografico')),
            ],
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('horariosAtencion', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)])),
                ('correo', models.EmailField(max_length=45, validators=[django.core.validators.MinLengthValidator(5)])),
                ('numeroTelefonico', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(7)])),
                ('direccion', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(10)])),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.departamento')),
            ],
        ),
    ]
