# Generated by Django 4.1.1 on 2022-10-04 01:39

import biblioteca.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='fechaDevolucion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fechaPrestamo',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 21, 39, 11, 621710)),
        ),
        migrations.AlterField(
            model_name='materialbibliografico',
            name='cantidadActual',
            field=models.PositiveSmallIntegerField(validators=[biblioteca.validators.no_cero]),
        ),
        migrations.AlterField(
            model_name='materialbibliografico',
            name='cantidadEjemplares',
            field=models.PositiveSmallIntegerField(validators=[biblioteca.validators.no_cero]),
        ),
        migrations.AlterField(
            model_name='materialbibliografico',
            name='fechaPublicacion',
            field=models.DateField(validators=[biblioteca.validators.fecha_menorActual]),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='ci',
            field=models.CharField(max_length=10, unique=True, validators=[biblioteca.validators.formato_CarnetBolivia]),
        ),
    ]
