# Generated by Django 4.1.1 on 2022-10-04 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_prestamo_fechadevolucion_prestamo_fechaprestamo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaLibros',
            new_name='CategoriaMaterial',
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechaPrestamo',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 21, 42, 43, 977259)),
        ),
    ]
