# Generated by Django 4.1.1 on 2022-10-04 01:47

import biblioteca.validators
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_alter_prestamo_fechaprestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteca',
            name='numeroTelefonico',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(7), biblioteca.validators.solo_numeros]),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechaPrestamo',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 21, 47, 5, 123865)),
        ),
    ]
