# Generated by Django 4.1.1 on 2022-10-04 17:39

import biblioteca.validators
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_alter_prestamo_fechaprestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialbibliografico',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.biblioteca'),
        ),
        migrations.AlterField(
            model_name='materialbibliografico',
            name='idioma',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechaDevolucion',
            field=models.DateTimeField(blank=True, null=True, validators=[biblioteca.validators.fecha_menorIgualActual]),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechaPrestamo',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 4, 13, 39, 7, 859924), validators=[biblioteca.validators.fecha_menorIgualActual]),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='numeroTelefonico',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(7), biblioteca.validators.solo_numeros]),
        ),
    ]
