# Generated by Django 4.1.1 on 2022-10-04 17:44

import biblioteca.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_alter_materialbibliografico_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialbibliografico',
            name='perteneceA',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.biblioteca'),
        ),
        migrations.AlterField(
            model_name='materialbibliografico',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.categoriamaterial'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechaPrestamo',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 4, 13, 44, 11, 824629), validators=[biblioteca.validators.fecha_menorIgualActual]),
        ),
    ]
